//Login
export const LOGIN='LOGIN'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'
//Sign up
export const SIGN_UP='SIGN_UP'
export const SIGN_UP_SUCCESS='SIGN_UP_SUCCESS'
export const SIGN_UP_FAILED='SIGN_UP_FAILED'
//Log out
export const LOG_OUT='LOG_OUT'
export const LOG_OUT_SUCCESS='LOG_OUT_SUCCESS'
export const LOG_OUT_FAILED='LOG_OUT_FAILED'
//Token has expired
export const TOKEN_EXPIRED='TOKEN_EXPIRED'
//Persist login state
export const PERSIST_LOGIN_STATE='PERSIST_LOGIN_STATE'
//get ALBUM info
export const GET_ALBUM='GET_ALBUM'
export const GET_ALBUM_SUCCESS='GET_ALBUM_SUCCESS'
export const GET_ALBUM_FAILED='GET_ALBUM_FAILED'
//Edit Album
export const EDIT_ALBUM='EDIT_ALBUM'
export const EDIT_ALBUM_SUCCESS='EDIT_ALBUM_SUCCESS'
export const EDIT_ALBUM_FAILED='EDIT_ALBUM_FAILED'
//Add image to album
export const ADD_IMAGE='ADD_IMAGE'
export const ADD_IMAGE_SUCCESS='ADD_IMAGE_SUCCESS'
export const ADD_IMAGE_FAILED='ADD_IMAGE_FAILED'
//Delete an image on album
export const DELETE_IMAGE='DELETE_IMAGE'
export const DELETE_IMAGE_SUCCESS='DELETE_IMAGE_SUCCESS'
export const DELETE_IMAGE_FAILED='DELETE_IMAGE_FAILED'
//Delete Album
export const DELETE_ALBUM='DELETE_ALBUM'
export const DELETE_ALBUM_SUCCESS='DELETE_ALBUM_SUCCESS'
export const DELETE_ALBUM_FAILED='DELETE_ALBUM_FAILED'
//Change password
export const CHANGE_PASSWORD='CHANGE_PASSWORD'
export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED='CHANGE_PASSWORD_FAILED'
//Up load image
export const UPLOAD='UPLOAD'
export const UPLOAD_SUCCESS='UPLOAD_SUCCESS'
export const UPLOAD_FAILED='UPLOAD_FAILED'
//